root: true
parser: '@typescript-eslint/parser'
env:
  node: true
  es2021: true
parserOptions:
  project: ./tsconfig.eslint.json
ignorePatterns:
  - dist
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
plugins:
  - '@typescript-eslint'
  - import
rules:
  no-underscore-dangle:
    - error
    - allowAfterThis: true
      allow:
        - _id
  import/extensions:
    - error
    - always
    - ignorePackages: true
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/no-redeclare': 'off'
  '@typescript-eslint/no-misused-promises':
    - error
    - checksVoidReturn:
        arguments: false
